name: Node.js CI

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name:
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies 
      run: npm ci

    - name: Run tests with coverage
      run: npm test

    - name: Upload coverage as artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage
